In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
import webbrowser

In [4]:
link = 'http://pandas.pydata.org/pandas-docs/version/0.20/io.html'
webbrowser.open(link)

True

In [5]:
df1 = pd.read_clipboard()

In [6]:
df1

   Format Type      Data Description          Reader        Writer
0         text                   CSV        read_csv        to_csv
1         text                  JSON       read_json       to_json
2         text                  HTML       read_html       to_html
3         text       Local clipboard  read_clipboard  to_clipboard
4       binary              MS Excel      read_excel      to_excel
5       binary           HDF5 Format        read_hdf        to_hdf
6       binary        Feather Format    read_feather    to_feather
7       binary               Msgpack    read_msgpack    to_msgpack
8       binary                 Stata      read_stata      to_stata
9       binary                   SAS        read_sas
10      binary  Python Pickle Format     read_pickle     to_pickle
11         SQL                   SQL        read_sql        to_sql
12         SQL      Google Big Query        read_gbq        to_gbq

In [9]:
df1.to_clipboard()

In [10]:
df1

   Format Type      Data Description          Reader        Writer
0         text                   CSV        read_csv        to_csv
1         text                  JSON       read_json       to_json
2         text                  HTML       read_html       to_html
3         text       Local clipboard  read_clipboard  to_clipboard
4       binary              MS Excel      read_excel      to_excel
5       binary           HDF5 Format        read_hdf        to_hdf
6       binary        Feather Format    read_feather    to_feather
7       binary               Msgpack    read_msgpack    to_msgpack
8       binary                 Stata      read_stata      to_stata
9       binary                   SAS        read_sas
10      binary  Python Pickle Format     read_pickle     to_pickle
11         SQL                   SQL        read_sql        to_sql
12         SQL      Google Big Query        read_gbq        to_gbq

In [11]:
df1.to_csv('df1.csv')

In [12]:
!dir

 驱动器 C 中的卷是 Win
 卷的序列号是 CE44-B535

 C:\Users\matingting 的目录

2022/02/16  09:50    <DIR>          .
2022/02/16  09:50    <DIR>          ..
2022/02/15  13:57    <DIR>          .android
2022/02/15  10:24            28,494 .bash_history
2021/12/30  10:04    <DIR>          .bifrost
2022/02/15  13:57    <DIR>          .BigNox
2021/08/20  14:10    <DIR>          .config
2021/09/28  21:09               190 .gitconfig
2022/02/16  09:45    <DIR>          .ipynb_checkpoints
2022/02/15  14:26    <DIR>          .ipython
2022/01/24  13:16    <DIR>          .jupyter
2022/02/15  10:16               104 .lesshst
2021/08/24  16:57    <DIR>          .umi3
2021/08/20  13:29    <DIR>          .vscode
2021/08/24  16:31               121 .yarnrc
2021/08/17  10:20    <DIR>          3D Objects
2021/09/27  16:54         8,294,826 app_download_native_report202108.sql
2022/02/15  15:58             9,468 Array.ipynb
2022/02/15  16:40            13,929 Array的input和output.ipynb
2021/08/17  10:20    <DIR>          Contacts
2021/11/04  11:24               300 d4ac4633ebd6440fa397b84f1bc94a3c.7z
2022/02/16  09:50            11,874 DataFrame IO.ipynb
2022/02/15  17:44            27,956 Dataframe.ipynb
2022/02/15  14:57             1,173 demo.ipynb
2022/02/16  09:49    <DIR>          Desktop
2022/02/16  09:50               539 df1.csv
2022/02/15  14:21    <DIR>          Documents
2021/10/09  16:04    <DIR>          Downloads
2021/08/17  10:20    <DIR>          Favorites
2021/11/22  16:04    <DIR>          go
2021/11/03  17:02                66 inittk.ini
2021/11/03  17:01                41 inst.ini
2021/08/17  10:20    <DIR>          Links
2021/08/17  10:20    <DIR>          Music
2021/11/03  17:01    <DIR>          Nox_share
2021/11/03  17:01                45 nuuid.ini
2021/08/12  16:00    <DIR>          OneDrive
2022/02/15  16:36               168 one_array.npy
2022/01/09  16:18    <DIR>          Pictures
2021/08/17  10:20    <DIR>          Saved Games
2021/08/17  10:20    <DIR>          Searches
2022/02/15  17:19            11,245 Series.ipynb
2022/02/15  16:37               610 two_array.npz
2021/11/03  17:01                53 useruid.ini
2021/08/17  10:20    <DIR>          Videos
2022/02/15  13:56    <DIR>          vmlogs
2022/02/15  16:35               187 x.pk1
2022/02/15  16:31            17,825 数组与矩阵运算.ipynb
2022/02/15  18:12            25,511 深入理解Series和Dataframe.ipynb
              22 个文件      8,444,725 字节
              27 个目录 52,511,346,688 可用字节

In [13]:
!more df1.csv

,Format Type,Data Description,Reader,Writer
0,text,CSV,read_csv,to_csv
1,text,JSON,read_json,to_json
2,text,HTML,read_html,to_html
3,text,Local clipboard,read_clipboard,to_clipboard
4,binary,MS Excel,read_excel,to_excel
5,binary,HDF5 Format,read_hdf,to_hdf
6,binary,Feather Format,read_feather,to_feather
7,binary,Msgpack,read_msgpack,to_msgpack
8,binary,Stata,read_stata,to_stata
9,binary,SAS,read_sas,
10,binary,Python Pickle Format,read_pickle,to_pickle
11,SQL,SQL,read_sql,to_sql
12,SQL,Google Big Query,read_gbq,to_gbq

In [14]:
df1.to_csv('df1.csv',index=False)

In [15]:
!dir

 驱动器 C 中的卷是 Win
 卷的序列号是 CE44-B535

 C:\Users\matingting 的目录

2022/02/16  09:52    <DIR>          .
2022/02/16  09:52    <DIR>          ..
2022/02/15  13:57    <DIR>          .android
2022/02/15  10:24            28,494 .bash_history
2021/12/30  10:04    <DIR>          .bifrost
2022/02/15  13:57    <DIR>          .BigNox
2021/08/20  14:10    <DIR>          .config
2021/09/28  21:09               190 .gitconfig
2022/02/16  09:45    <DIR>          .ipynb_checkpoints
2022/02/15  14:26    <DIR>          .ipython
2022/01/24  13:16    <DIR>          .jupyter
2022/02/15  10:16               104 .lesshst
2021/08/24  16:57    <DIR>          .umi3
2021/08/20  13:29    <DIR>          .vscode
2021/08/24  16:31               121 .yarnrc
2021/08/17  10:20    <DIR>          3D Objects
2021/09/27  16:54         8,294,826 app_download_native_report202108.sql
2022/02/15  15:58             9,468 Array.ipynb
2022/02/15  16:40            13,929 Array的input和output.ipynb
2021/08/17  10:20    <DIR>          Contacts
2021/11/04  11:24               300 d4ac4633ebd6440fa397b84f1bc94a3c.7z
2022/02/16  09:52            16,374 DataFrame IO.ipynb
2022/02/15  17:44            27,956 Dataframe.ipynb
2022/02/15  14:57             1,173 demo.ipynb
2022/02/16  09:49    <DIR>          Desktop
2022/02/16  09:52               509 df1.csv
2022/02/15  14:21    <DIR>          Documents
2021/10/09  16:04    <DIR>          Downloads
2021/08/17  10:20    <DIR>          Favorites
2021/11/22  16:04    <DIR>          go
2021/11/03  17:02                66 inittk.ini
2021/11/03  17:01                41 inst.ini
2021/08/17  10:20    <DIR>          Links
2021/08/17  10:20    <DIR>          Music
2021/11/03  17:01    <DIR>          Nox_share
2021/11/03  17:01                45 nuuid.ini
2021/08/12  16:00    <DIR>          OneDrive
2022/02/15  16:36               168 one_array.npy
2022/01/09  16:18    <DIR>          Pictures
2021/08/17  10:20    <DIR>          Saved Games
2021/08/17  10:20    <DIR>          Searches
2022/02/15  17:19            11,245 Series.ipynb
2022/02/15  16:37               610 two_array.npz
2021/11/03  17:01                53 useruid.ini
2021/08/17  10:20    <DIR>          Videos
2022/02/15  13:56    <DIR>          vmlogs
2022/02/15  16:35               187 x.pk1
2022/02/15  16:31            17,825 数组与矩阵运算.ipynb
2022/02/15  18:12            25,511 深入理解Series和Dataframe.ipynb
              22 个文件      8,449,195 字节
              27 个目录 52,507,443,200 可用字节

In [16]:
!more df1.csv

Format Type,Data Description,Reader,Writer
text,CSV,read_csv,to_csv
text,JSON,read_json,to_json
text,HTML,read_html,to_html
text,Local clipboard,read_clipboard,to_clipboard
binary,MS Excel,read_excel,to_excel
binary,HDF5 Format,read_hdf,to_hdf
binary,Feather Format,read_feather,to_feather
binary,Msgpack,read_msgpack,to_msgpack
binary,Stata,read_stata,to_stata
binary,SAS,read_sas,
binary,Python Pickle Format,read_pickle,to_pickle
SQL,SQL,read_sql,to_sql
SQL,Google Big Query,read_gbq,to_gbq

In [17]:
df2 = pd.read_csv('df1.csv')

In [18]:
df2

   Format Type      Data Description          Reader        Writer
0         text                   CSV        read_csv        to_csv
1         text                  JSON       read_json       to_json
2         text                  HTML       read_html       to_html
3         text       Local clipboard  read_clipboard  to_clipboard
4       binary              MS Excel      read_excel      to_excel
5       binary           HDF5 Format        read_hdf        to_hdf
6       binary        Feather Format    read_feather    to_feather
7       binary               Msgpack    read_msgpack    to_msgpack
8       binary                 Stata      read_stata      to_stata
9       binary                   SAS        read_sas
10      binary  Python Pickle Format     read_pickle     to_pickle
11         SQL                   SQL        read_sql        to_sql
12         SQL      Google Big Query        read_gbq        to_gbq

In [19]:
df1.to_json()

'{"Format Type":{"0":"text","1":"text","2":"text","3":"text","4":"binary","5":"binary","6":"binary","7":"binary","8":"binary","9":"binary","10":"binary","11":"SQL","12":"SQL"},"Data Description":{"0":"CSV","1":"JSON","2":"HTML","3":"Local clipboard","4":"MS Excel","5":"HDF5 Format","6":"Feather Format","7":"Msgpack","8":"Stata","9":"SAS","10":"Python Pickle Format","11":"SQL","12":"Google Big Query"},"Reader":{"0":"read_csv","1":"read_json","2":"read_html","3":"read_clipboard","4":"read_excel","5":"read_hdf","6":"read_feather","7":"read_msgpack","8":"read_stata","9":"read_sas","10":"read_pickle","11":"read_sql","12":"read_gbq"},"Writer":{"0":"to_csv","1":"to_json","2":"to_html","3":"to_clipboard","4":"to_excel","5":"to_hdf","6":"to_feather","7":"to_msgpack","8":"to_stata","9":" ","10":"to_pickle","11":"to_sql","12":"to_gbq"}}'

In [20]:
pd.read_json(df1.to_json())

   Format Type      Data Description          Reader        Writer
0         text                   CSV        read_csv        to_csv
1         text                  JSON       read_json       to_json
2         text                  HTML       read_html       to_html
3         text       Local clipboard  read_clipboard  to_clipboard
4       binary              MS Excel      read_excel      to_excel
5       binary           HDF5 Format        read_hdf        to_hdf
6       binary        Feather Format    read_feather    to_feather
7       binary               Msgpack    read_msgpack    to_msgpack
8       binary                 Stata      read_stata      to_stata
9       binary                   SAS        read_sas
10      binary  Python Pickle Format     read_pickle     to_pickle
11         SQL                   SQL        read_sql        to_sql
12         SQL      Google Big Query        read_gbq        to_gbq

In [22]:
df1.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Format Type</th>\n      <th>Data Description</th>\n      <th>Reader</th>\n      <th>Writer</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>text</td>\n      <td>CSV</td>\n      <td>read_csv</td>\n      <td>to_csv</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>text</td>\n      <td>JSON</td>\n      <td>read_json</td>\n      <td>to_json</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>text</td>\n      <td>HTML</td>\n      <td>read_html</td>\n      <td>to_html</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>text</td>\n      <td>Local clipboard</td>\n      <td>read_clipboard</td>\n      <td>to_clipboard</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>binary</td>\n      <td>MS Excel</td>\n      <td>read_excel</td>\n      <td>to_excel</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>binary</td>\n      <td>HDF5 Format</td>\n      <td>read_hdf</td>\n      <td>to_hdf</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>binary</td>\n      <td>Feather Format</td>\n      <td>read_feather</td>\n      <td>to_feather</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>binary</td>\n      <td>Msgpack</td>\n      <td>read_msgpack</td>\n      <td>to_msgpack</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>binary</td>\n      <td>Stata</td>\n      <td>read_stata</td>\n      <td>to_stata</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>binary</td>\n      <td>SAS</td>\n      <td>read_sas</td>\n      <td></td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>binary</td>\n      <td>Python Pickle Format</td>\n      <td>read_pickle</td>\n      <td>to_pickle</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>SQL</td>\n      <td>SQL</td>\n      <td>read_sql</td>\n      <td>to_sql</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>SQL</td>\n      <td>Google Big Query</td>\n      <td>read_gbq</td>\n      <td>to_gbq</td>\n    </tr>\n  </tbody>\n</table>'

In [23]:
df1.to_html('df1.html')

In [24]:
!dir

 驱动器 C 中的卷是 Win
 卷的序列号是 CE44-B535

 C:\Users\matingting 的目录

2022/02/16  09:55    <DIR>          .
2022/02/16  09:55    <DIR>          ..
2022/02/15  13:57    <DIR>          .android
2022/02/15  10:24            28,494 .bash_history
2021/12/30  10:04    <DIR>          .bifrost
2022/02/15  13:57    <DIR>          .BigNox
2021/08/20  14:10    <DIR>          .config
2021/09/28  21:09               190 .gitconfig
2022/02/16  09:45    <DIR>          .ipynb_checkpoints
2022/02/15  14:26    <DIR>          .ipython
2022/01/24  13:16    <DIR>          .jupyter
2022/02/15  10:16               104 .lesshst
2021/08/24  16:57    <DIR>          .umi3
2021/08/20  13:29    <DIR>          .vscode
2021/08/24  16:31               121 .yarnrc
2021/08/17  10:20    <DIR>          3D Objects
2021/09/27  16:54         8,294,826 app_download_native_report202108.sql
2022/02/15  15:58             9,468 Array.ipynb
2022/02/15  16:40            13,929 Array的input和output.ipynb
2021/08/17  10:20    <DIR>          Contacts
2021/11/04  11:24               300 d4ac4633ebd6440fa397b84f1bc94a3c.7z
2022/02/16  09:54            32,520 DataFrame IO.ipynb
2022/02/15  17:44            27,956 Dataframe.ipynb
2022/02/15  14:57             1,173 demo.ipynb
2022/02/16  09:49    <DIR>          Desktop
2022/02/16  09:52               509 df1.csv
2022/02/16  09:55             1,954 df1.html
2022/02/15  14:21    <DIR>          Documents
2021/10/09  16:04    <DIR>          Downloads
2021/08/17  10:20    <DIR>          Favorites
2021/11/22  16:04    <DIR>          go
2021/11/03  17:02                66 inittk.ini
2021/11/03  17:01                41 inst.ini
2021/08/17  10:20    <DIR>          Links
2021/08/17  10:20    <DIR>          Music
2021/11/03  17:01    <DIR>          Nox_share
2021/11/03  17:01                45 nuuid.ini
2021/08/12  16:00    <DIR>          OneDrive
2022/02/15  16:36               168 one_array.npy
2022/01/09  16:18    <DIR>          Pictures
2021/08/17  10:20    <DIR>          Saved Games
2021/08/17  10:20    <DIR>          Searches
2022/02/15  17:19            11,245 Series.ipynb
2022/02/15  16:37               610 two_array.npz
2021/11/03  17:01                53 useruid.ini
2021/08/17  10:20    <DIR>          Videos
2022/02/15  13:56    <DIR>          vmlogs
2022/02/15  16:35               187 x.pk1
2022/02/15  16:31            17,825 数组与矩阵运算.ipynb
2022/02/15  18:12            25,511 深入理解Series和Dataframe.ipynb
              23 个文件      8,467,295 字节
              27 个目录 52,497,199,104 可用字节

In [25]:
df1.to_excel('df1.xlsx')